### PR TITLE
Create your own Enumerable 

### PR DESCRIPTION
**Pull request by pushkar1995**
This is a pair programming project and the participants are:
Pushkar Gautam & Mumbere Habert

This pull request concerns the implementation of a subset of the functionality of Enumerable, with three modules.

Within this branch, we have:
 - The implementation of a subset of the functionality of Enumerable, with three modules:
#all
#any
m#filter

### CODE REVIEW

**Comment by topeogunleye** [comment]
Hi @pushkar1995, @mumbereh,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## GitHub flow Not Used ⚠️

- Pull request is to be made from the feature branch into the main not into the dev or development branch

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by pushkar1995** [comment]
@topeogunleye I have changed my base branch back to main from the custom base branch 'dev' I have created as per the suggestion of the reviewer.

**Comment by topeogunleye** [comment]
> @topeogunleye I have changed my base branch back to main from the custom base branch 'dev' I have created as per the suggestion of the reviewer.

@pushkar1995 That's Awesome. Please kindly submit your project for a review

**Review by frank1738 — APPROVED** [review]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

✅ Enumerable works as expected 👍

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
